# Generated by Django 4.2.13 on 2024-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
            ],
            
         ),
        
        # migrations.CreateModel(
        #     name='Usuario',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('nombre', models.CharField(max_length=40)),
        #         ('apellido', models.CharField(max_length=40)),
        #         ('correo', models.CharField(max_length=40)),
        #     ],
        # ),
    ]
